sudo: required
language: java
jdk:
- oraclejdk8
services:
- docker
addons:
  hosts:
  - docker
before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
- docker save -o $HOME/docker_cache/docker.tar stfdigital-autuacao-peticionamento $(docker history -q stfdigital-autuacao-peticionamento | tail -n +2 | grep -v \<missing\> | tr '\n' ' ')
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - node_cache
  - node_modules
  - "$HOME/docker_cache"
before_install:
- "./scripts/upgrade-docker.sh"
- mkdir -p $HOME/docker_cache
install: docker load -i $HOME/docker_cache/docker.tar || true
script: gradle docker && gradle gulpTestUnit && ./scripts/test-e2e.sh
notifications:
  slack:
    secure: J+SnEKgkdotNZyd/U57nEylQPHPMo4gaaCfbkTXmI4VESsZybWox267g+BJxzzgF0111g3/qk5GtC+a5/V5Na/YVkTugpxZ8jWH6VIcqR5q9IOzfZoM+WHcJmxdB0x5g9QtLG759xBt91BghrVdsc0TV4VUhxWYndJiKNEdDfH2U9PhkurkOKMD73fDSsPLQTxreeB/mcuGxQhD1YQhiuPIZFKqIEQKu3golavqkvAb8LBaIkELKzQTH84JUuOajFY0p88sBa1OzY2AFkeb7yWKokp9zy342G/YaKxPXHyXI0E64D1a0IZoWhmjYo/harVpCM520fo8CetCkt0eGsQrk5RQ1qaJn5jvehLDfBnvRn22vxFABwxwLiHIBkhhZP0Cm/ZwAbyUv/PVZQi/j6/LmEPnROU7IBcWm1FfWhBkY0iNgAMU0QS169JLB0qvPZBSKjR7bw+SdiyRZwfPFIkEwS3uj4SFNPNjxSXkBR5yI89PeQ4cR+0H01FyU1hh0FQM1e8EYW50JIpIxYof47DSmwZdmrXnr9M/C4FGLUpXttsPe4ogaNmOFmwXlxrHPil+B9AJKF8Q5lHOGUkWqelFLHzx2N9kM9C01VLmYD/WcM/kWSVvNnCVF+pN4w22ehyD/xuChBYM/YhqZp3nnf816nvR1Bc/KQ8RBlBlbenw=
