# Extende a configuração para rodar os testes e2e.
# Deve ser rodado em combinação com shared/compose/docker-compose.e2e.base.yml
version: '2'
services:
  peticionamento:
    extends:
      file: shared/compose/common.yml
      service: peticionamento
    image: stfdigital-autuacao-peticionamento
    environment:
     - spring.profiles.active=development,docker,e2e
    depends_on:
     - rabbit
     - discovery
