# Define a configuração para rodar esse contexto construído localmente
version: '2'
services:
  peticionamento:
    extends:
      file: compose/shared/common.yml
      service: peticionamento
    image: stfdigital-autuacao-peticionamento
    depends_on:
     - rabbit
     - discovery